### ISSUE TITLE
Note on HRAM/IO R/W

### ISSUE THREAD

**Issue by PikalaxALT** [mattcurrie/mgbdis#11]
From README.md:

> RGBDS optimises instructions like LD [$FF40],a to LDH [$FF00+40],a, so these are encoded as data bytes using a macro to ensure exact reproduction of the original ROM (thanks to ISSOtm). RGBDS >= v0.3.7 has an option to disable this optimisation. Use --disable-auto-ldh with mgbdis to disable the macro.

This only applies to constant expressions. If you instead export the symbol from an HRAM section, it'll use the 3-byte ld instruction.

**Comment by mattcurrie** [comment]
Ah yes, thanks, I will tweak the notes in the readme
