### ISSUE TITLE
bdm source/win32 build

### ISSUE THREAD

**Issue by rofl0r** [mattcurrie/mgbdis#26]
i would like to use bdm to create a sym file for this disassembler, but to my surprise the windows build (couldnt find source) is win64 only. would it be possible to provide a win32 build so i can use it in wine ? if the source is available somewhere, that would be even better of course.

**Comment by mattcurrie** [comment]
Hi there, 

The Windows and macOS builds of BDM don't currently support generating .sym files, but it shouldn't be too hard to add. You can try using the web demo of BDM in the meantime: https://mattcurrie.com/bdm-demo/

I've looked into 32-bit Windows builds and it seems to be fairly straightforward to do with the cross-compiler setup I'm using. I'll add arm64 builds for macOS at the same time.

No source available at the moment - maybe one day when I have some time available to work on BDM.

**Comment by rofl0r** [comment]
hi,

> it seems to be fairly straightforward to do with the cross-compiler setup I'm using. I'll add arm64 builds for macOS at the same time.

> maybe one day when I have some time available to work on BDM

that's good news, thanks.

> You can try using the web demo of BDM in the meantime: https://mattcurrie.com/bdm-demo/

i didn't try that because it seems awkward to play through an entire game in the browser, so it can properly detect all data and gfx. do the sym files produced by BDM include GFX (tiles, sprites) locations even ?

**Comment by mattcurrie** [comment]
Hi there,

I've now added win32 and Apple Silicon builds: https://mattcurrie.com/bdm/

You can generate a .sym file by pressing W while playing a game.

It should be able to detect code and data, but the graphics (tile data) detection will be a bit hit or miss depending on the complexity of what the game is doing. e.g. it won't handle compressed tile data.

**Comment by rofl0r** [comment]
cool, thanks!
