### ISSUE TITLE
Tetris fails to match

### ISSUE THREAD

**Issue by mattbruv** [mattcurrie/mgbdis#9]
Original ROM is Tetris with a MD5 hash of `084f1e457749cdec86183189bd88ce69`

Output ROM game.gb has a MD5 hash of `389d39cb232bebe3ff7d4ccbc6269a82`

See [here](https://www.diffnow.com/?report=6ws24) for a difference comparison. 101 differences: 104 bytes

**Comment by mattcurrie** [comment]
These off by one errors are due to an issue in RGBDS 0.3.6: rednex/rgbds/issues/259

I'll add a note in the readme about this.
